In [1]:
import numpy as np
import pandas as pd

https://www.nongnet.or.kr/anss/splyInfo.do  - 농산물 가격 데이터셋 제공

농업 데이터 가격및 거래량과 날씨간의 상관관계 비교

In [2]:
train = pd.read_csv("train.csv")
private = pd.read_csv("private_data.csv")

In [3]:
train

,date,요일,배추_거래량(kg),배추_가격(원/kg),무_거래량(kg),무_가격(원/kg),양파_거래량(kg),양파_가격(원/kg),건고추_거래량(kg),건고추_가격(원/kg),...,청상추_거래량(kg),청상추_가격(원/kg),백다다기_거래량(kg),백다다기_가격(원/kg),애호박_거래량(kg),애호박_가격(원/kg),캠벨얼리_거래량(kg),캠벨얼리_가격(원/kg),샤인마스캇_거래량(kg),샤인마스캇_가격(원/kg)
0,2016-01-01,금요일,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2016-01-02,토요일,80860.0,329.0,80272.0,360.0,122787.5,1281.0,3.0,11000.0,...,5125.0,9235.0,434.0,2109.0,19159.0,2414.0,880.0,2014.0,0.0,0.0
2,2016-01-03,일요일,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2016-01-04,월요일,1422742.5,478.0,1699653.7,382.0,2315079.0,1235.0,699.0,4464.0,...,38525.5,7631.0,500702.0,2046.0,620539.0,2018.0,2703.8,3885.0,0.0,0.0
4,2016-01-05,화요일,1167241.0,442.0,1423482.3,422.0,2092960.1,1213.0,1112.6,4342.0,...,32615.0,6926.0,147638.0,2268.0,231958.0,2178.0,8810.0,2853.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1728,2020-09-24,목요일,1856965.0,1839.0,2055640.0,990.0,2281429.2,990.0,2818.4,19101.0,...,50730.0,4509.0,282212.3,3001.0,313139.7,3426.0,504242.6,3620.0,283196.9,10940.0
1729,2020-09-25,금요일,1880095.5,1789.0,1879261.0,1011.0,2074513.0,955.0,1887.1,23095.0,...,54322.0,4178.0,312214.8,2999.0,362741.0,3357.0,479683.1,3618.0,303779.6,10844.0
1730,2020-09-26,토요일,1661090.9,1760.0,1709385.7,1075.0,2089081.2,961.0,959.0,22510.0,...,61213.0,3770.0,327395.8,3065.0,390361.2,3092.0,521493.8,3691.0,313295.7,10636.0
1731,2020-09-27,일요일,25396.0,3066.0,38222.0,1139.0,18240.0,1056.0,60.0,22333.0,...,144.0,4076.0,285.0,3707.0,2464.0,3252.0,21717.0,3567.0,9734.0,10699.0
1732,2020-09-28,월요일,2405051.9,1867.0,2747519.5,1147.0,2235784.7,964.0,1630.6,22022.0,...,84155.0,4167.0,554862.6,2873.0,667745.0,2782.0,601841.0,3761.0,382263.4,10998.0

In [4]:
private

,date,요일,배추_거래량(kg),배추_가격(원/kg),무_거래량(kg),무_가격(원/kg),양파_거래량(kg),양파_가격(원/kg),건고추_거래량(kg),건고추_가격(원/kg),...,청상추_거래량(kg),청상추_가격(원/kg),백다다기_거래량(kg),백다다기_가격(원/kg),애호박_거래량(kg),애호박_가격(원/kg),캠벨얼리_거래량(kg),캠벨얼리_가격(원/kg),샤인마스캇_거래량(kg),샤인마스캇_가격(원/kg)
0,2020-11-06,금요일,2051420.6,493.0,2764127.3,487.0,1969669.2,1138.0,958.0,22510.0,...,42634.0,1959.0,290660.8,1290.0,318723.1,1530.0,23697.0,2797.0,70824.0,10514.0
1,2020-11-07,토요일,2042138.9,442.0,2666318.3,479.0,1705453.2,1157.0,513.4,22581.0,...,48052.0,1893.0,342790.2,1189.0,285808.6,1433.0,17876.0,3291.0,63136.5,10599.0
2,2020-11-08,일요일,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-11-09,월요일,2848530.8,456.0,3727873.7,438.0,2133235.1,1166.0,1800.7,22878.0,...,52472.5,2006.0,497814.6,1211.0,478405.1,1500.0,22151.4,3118.0,65780.5,10830.0
4,2020-11-10,화요일,2255125.2,471.0,3199634.2,428.0,1793176.8,1167.0,1527.4,22083.0,...,48767.1,2072.0,243682.9,1315.0,294449.5,1545.0,14071.5,4010.0,69389.7,10764.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,2021-08-19,목요일,993076.5,626.0,946342.5,474.0,1730850.5,827.0,7359.3,18764.0,...,36122.5,6997.0,321003.2,2398.0,250118.5,1690.0,395434.9,3750.0,88847.0,12227.0
287,2021-08-20,금요일,1159824.2,578.0,1042244.6,458.0,1551516.8,774.0,7818.5,18152.0,...,36079.0,6769.0,351506.5,2318.0,274419.3,1866.0,424203.7,3671.0,91037.4,11985.0
288,2021-08-21,토요일,977115.9,611.0,928502.8,451.0,1176762.2,780.0,5091.1,17569.0,...,32672.0,7257.0,354724.8,2229.0,255663.2,1950.0,398782.2,3518.0,82161.8,11519.0
289,2021-08-22,일요일,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
290,2021-08-23,월요일,130467.4,644.0,141745.0,501.0,213791.4,756.0,980.6,17800.0,...,5998.0,6841.0,56961.0,2142.0,53674.0,1782.0,95703.0,3506.0,19483.2,11100.0

In [7]:
df = pd.read_csv("AT_TSALET_ALL_202108.csv")

In [8]:
df

,SALEDATE,WHSAL_NM,CMP_NM,PUM_NM,KIND_NM,DAN_NM,POJ_NM,SIZE_NM,LV_NM,SAN_NM,DANQ,QTY,COST,TOT_QTY,TOT_AMT
0,20210810,인천삼산도매,경인농산,깻잎,깻잎(일반),kg,상자,.,특,충청남도 논산시,2.0,3.0,16000,6.0,48000.0
1,20210810,인천삼산도매,경인농산,깻잎,깻잎(일반),kg,상자,.,특,충청남도 논산시,2.0,3.0,18000,6.0,54000.0
2,20210810,인천삼산도매,경인농산,깻잎,깻잎(일반),kg,상자,.,특,충청남도 논산시,3.0,4.0,16000,12.0,64000.0
3,20210810,인천삼산도매,경인농산,깻잎,깻잎순,kg,상자,.,특,충청남도,3.0,4.0,13000,12.0,52000.0
4,20210810,인천삼산도매,경인농산,깻잎,깻잎(일반),kg,상자,.,특,충청남도,3.0,1.0,8000,3.0,8000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2365201,20210821,서울강서도매,강서청과,바나나,바나나(수입),kg,.,1개(내_뿌리),.,NaN,13.0,19.0,18000,247.0,342000.0
2365202,20210821,서울강서도매,강서청과,바나나,바나나(수입),kg,.,1개(내_뿌리),.,NaN,13.0,15.0,18000,195.0,270000.0
2365203,20210821,서울강서도매,강서청과,바나나,바나나(수입),kg,.,1개(내_뿌리),.,NaN,13.0,5.0,18000,65.0,90000.0
2365204,20210821,서울강서도매,강서청과,바나나,바나나(수입),kg,.,1개(내_뿌리),.,NaN,13.0,5.0,18000,65.0,90000.0
2365205,20210821,서울강서도매,강서청과,바나나,바나나(수입),kg,.,1개(내_뿌리),.,NaN,13.0,4.0,18000,52.0,72000.0

https://www.data.go.kr/data/15078057/openapi.do - 농업 기상 관측데이터

https://dacon.io/competitions/official/235801/codeshare/3350?page=1&dtype=recent